name: PHP Composer

on:
  push: ~
  pull_request: ~

jobs:
  build:
    name: Run tests on ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, psalm

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - run: composer install --no-progress --prefer-dist --no-suggest

      - run: psalm --output-format=github
        if: ${{ matrix.php == '8.0' }}

      - run: vendor/bin/phpunit
